---
title: "Quantitative Finance Notes"
author: "Benjamin Burch"
output:
  html_notebook: 
    toc: yes
  html_document:
    toc: yes
    toc_float: yes
---

# Time Series

## Libraries

* xts - time series index + matrix object; as.xts looks like a very useful function
* zoo
* PerformanceAnalytics - Econometric tools

## Notes

* Use saveRDS for zoo objects
* zoo has read and write functions

### xts

* xts functions "first" and "last" are analogous to head and tail e.g. last(data, "5 months")
* "merge" allow for database style joins
* ts and zoo define lag with the opposite sign of xts
* "lag" and "diff" functions allow for complex math
* to.period will give OHLC values (Open, High, Low, Close) by default
* "rollapply" colaculated rolling sums, means, etc.
* index is seconds from 1970-01-01
* "periodicity" - estimated stucture of timeseries data
* "align.time" - round to specified periodicity
* get weekends: index <- which(.indexwday(x) == 0 | .indexwday(x) == 6)

* an example
```{r}
library(xts)
library(PerformanceAnalytics)

# monthly xts hedge fund index returns
data(edhec)

# 6 month slice
edhec["199701/199706"]

```

* white noise - constant mean and variance, no pattern; can use arima.sim to create white noise
* ARIMA - Auto-regressive integrated moving average